/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
//    public String getGreeting() {
//        return "Hello world.";
//    }

    public static void main(String[] args) {
    	Car car = new Car("v8","tyre");
    	car.start();

    	SportsCar sportsCar = new SportsCar("light","v8","tyre");
    	sportsCar.start(); 
    	
    	Truck truck = new Truck("v8","tyre","test");
    	truck.start();
    	truck.load();
    	
    }
}
